/*
time: 20250322
author: you P
email: yolandaping1224@gmail.com
*/


global proc string pyFindOtherSide(
    string $joint,
    string $lKeyA[],
    string $rKeyA[]
) {

    int $count = min(size($lKeyA), size($rKeyA));

    for ($i = 0; $i < $count; $i++) {

        if (`gmatch $joint ("*" + $lKeyA[$i] + "*")`) {

            return `substitute $lKeyA[$i] $joint $rKeyA[$i]`;
        }
    }

    return "";
}